# Generated by Django 4.2.7 on 2023-11-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_prompt',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='strive.feedback'),
        ),
        migrations.AlterField(
            model_name='sei',
            name='challenge_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='strive.challenge_prompt'),
        ),
    ]
