# Generated by Django 4.2.7 on 2023-11-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strive', '0002_alter_challenge_prompt_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sei',
            name='challenge_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sei_prompts', to='strive.challenge_prompt'),
        ),
        migrations.CreateModel(
            name='Ux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('challenge_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ux_prompts', to='strive.challenge_prompt')),
            ],
        ),
    ]
