# Generated by Django 4.2.7 on 2023-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strive', '0003_alter_sei_challenge_prompt_ux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
